// Code generated by internal/jitvm/gen from vm.go; DO NOT EDIT.

package lua

import "fmt"

// executeSwitchJIT is executeSwitch for states that compile. It runs
// compiled code when it reaches an instruction the JIT patched in.
func (l *State) executeSwitchJIT() {
	ci := l.callInfo
	frame, closure, constants := newFrame(l, ci)
	code, ip := closure.prototype.execCode(), ci.savedPC
	for {
		i := code[ip]
		ip++
		ci.savedPC = ip
		if l.hookMask&(MaskLine|MaskCount) != 0 {
			if l.hookCount--; l.hookCount == 0 || l.hookMask&MaskLine != 0 {
				l.traceExecution()
				frame = ci.frame
			}
		}
		if i.opCode() >= opJITCount { // patched in by the JIT; see jit.go
			i, ip = l.jitInstruction(closure, frame, constants, i, ip)
		}
		switch i.opCode() {
		case opMove:
			frame[i.a()] = frame[i.b()]
		case opLoadConstant:
			frame[i.a()] = constants[i.bx()]
		case opLoadConstantEx:
			frame[i.a()] = constants[expectOp(code[ip], opExtraArg).ax()]
			ip++
		case opLoadBool:
			frame[i.a()] = boolValue(i.b() != 0)
			if i.c() != 0 {
				ip++
			}
		case opLoadNil:
			a, b := i.a(), i.b()
			clear(frame[a : a+b+1])
		case opGetUpValue:
			frame[i.a()] = closure.upValue(i.b())
		case opGetTableUp:
			tmp := l.tableAt(closure.upValue(i.b()), k(i.c(), constants, frame))
			frame = ci.frame
			frame[i.a()] = tmp
		case opGetTable:
			tmp := l.tableAt(frame[i.b()], k(i.c(), constants, frame))
			frame = ci.frame
			frame[i.a()] = tmp
		case opSetTableUp:
			l.setTableAt(closure.upValue(i.a()), k(i.b(), constants, frame), k(i.c(), constants, frame))
			frame = ci.frame
		case opSetUpValue:
			closure.setUpValue(i.b(), frame[i.a()])
		case opSetTable:
			l.setTableAt(frame[i.a()], k(i.b(), constants, frame), k(i.c(), constants, frame))
			frame = ci.frame
		case opNewTable:
			a := i.a()
			b, c := float8(i.b()), float8(i.c())
			frame[a] = objectValue(newTableAt(&closure.prototype.fields[ip-1], intFromFloat8(b), intFromFloat8(c)))
			clear(frame[a+1:])
		case opSelf:
			a, t := i.a(), frame[i.b()]
			tmp := l.tableAt(t, k(i.c(), constants, frame))
			frame = ci.frame
			frame[a+1], frame[a] = t, tmp
		case opGetField:
			t, key := frame[i.b()], constants[i.c()]
			if v, ok := getField(t, key, &closure.prototype.fields[ip-1]); ok {
				frame[i.a()] = v
				break
			}
			tmp := l.tableAt(t, key)
			frame = ci.frame
			frame[i.a()] = tmp
		case opGetFieldUp:
			t, key := closure.upValue(i.b()), constants[i.c()]
			if v, ok := getField(t, key, &closure.prototype.fields[ip-1]); ok {
				frame[i.a()] = v
				break
			}
			tmp := l.tableAt(t, key)
			frame = ci.frame
			frame[i.a()] = tmp
		case opSelfField:
			a, t, key := i.a(), frame[i.b()], constants[i.c()]
			if v, ok := getField(t, key, &closure.prototype.fields[ip-1]); ok {
				frame[a+1], frame[a] = t, v
				break
			}
			tmp := l.tableAt(t, key)
			frame = ci.frame
			frame[a+1], frame[a] = t, tmp
		case opSetField:
			t, key, v := frame[i.a()], constants[i.b()], k(i.c(), constants, frame)
			if !setField(t, key, v, &closure.prototype.fields[ip-1]) {
				l.setTableAt(t, key, v)
				frame = ci.frame
			}
		case opSetFieldUp:
			t, key, v := closure.upValue(i.a()), constants[i.b()], k(i.c(), constants, frame)
			if !setField(t, key, v, &closure.prototype.fields[ip-1]) {
				l.setTableAt(t, key, v)
				frame = ci.frame
			}
		case opAdd:
			b, c := k(i.b(), constants, frame), k(i.c(), constants, frame)
			if b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() + c.f())
				break
			}
			tmp := l.arith(b, c, tmAdd)
			frame = ci.frame
			frame[i.a()] = tmp
		case opSub:
			b, c := k(i.b(), constants, frame), k(i.c(), constants, frame)
			if b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() - c.f())
				break
			}
			tmp := l.arith(b, c, tmSub)
			frame = ci.frame
			frame[i.a()] = tmp
		case opMul:
			b, c := k(i.b(), constants, frame), k(i.c(), constants, frame)
			if b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() * c.f())
				break
			}
			tmp := l.arith(b, c, tmMul)
			frame = ci.frame
			frame[i.a()] = tmp
		case opDiv:
			b, c := k(i.b(), constants, frame), k(i.c(), constants, frame)
			if b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() / c.f())
				break
			}
			tmp := l.arith(b, c, tmDiv)
			frame = ci.frame
			frame[i.a()] = tmp
		case opMod:
			b, c := k(i.b(), constants, frame), k(i.c(), constants, frame)
			if b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(arith(OpMod, b.f(), c.f()))
				break
			}
			tmp := l.arith(b, c, tmMod)
			frame = ci.frame
			frame[i.a()] = tmp
		case opPow:
			b, c := k(i.b(), constants, frame), k(i.c(), constants, frame)
			if b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(arith(OpPow, b.f(), c.f()))
				break
			}
			tmp := l.arith(b, c, tmPow)
			frame = ci.frame
			frame[i.a()] = tmp
		case opAddRR:
			if b, c := frame[i.b()], frame[i.c()]; b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() + c.f())
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmAdd)
			}
		case opAddRK:
			if b, c := frame[i.b()], constants[i.c()]; b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() + c.f())
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmAdd)
			}
		case opAddKR:
			if b, c := constants[i.b()], frame[i.c()]; b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() + c.f())
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmAdd)
			}
		case opMulAddRKR:
			if b, c := frame[i.b()], constants[i.c()]; b.isNumber() && c.isNumber() {
				r := b.f() * c.f()
				frame[i.a()] = numberValue(r)
				if j := code[ip]; l.hookMask&(MaskLine|MaskCount) == 0 {
					if d := frame[j.c()]; d.isNumber() {
						frame[j.a()] = numberValue(r + d.f())
						ip++
					}
				}
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmMul)
			}
		case opSubRR:
			if b, c := frame[i.b()], frame[i.c()]; b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() - c.f())
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmSub)
			}
		case opSubRK:
			if b, c := frame[i.b()], constants[i.c()]; b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() - c.f())
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmSub)
			}
		case opSubKR:
			if b, c := constants[i.b()], frame[i.c()]; b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() - c.f())
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmSub)
			}
		case opMulRR:
			if b, c := frame[i.b()], frame[i.c()]; b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() * c.f())
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmMul)
			}
		case opMulRK:
			if b, c := frame[i.b()], constants[i.c()]; b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() * c.f())
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmMul)
			}
		case opMulKR:
			if b, c := constants[i.b()], frame[i.c()]; b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() * c.f())
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmMul)
			}
		case opDivRR:
			if b, c := frame[i.b()], frame[i.c()]; b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() / c.f())
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmDiv)
			}
		case opDivRK:
			if b, c := frame[i.b()], constants[i.c()]; b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() / c.f())
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmDiv)
			}
		case opDivKR:
			if b, c := constants[i.b()], frame[i.c()]; b.isNumber() && c.isNumber() {
				frame[i.a()] = numberValue(b.f() / c.f())
			} else {
				frame = l.arithInto(ci, i.a(), b, c, tmDiv)
			}
		case opUnaryMinus:
			if b := frame[i.b()]; b.isNumber() {
				frame[i.a()] = numberValue(-b.f())
			} else {
				tmp := l.arith(b, b, tmUnaryMinus)
				frame = ci.frame
				frame[i.a()] = tmp
			}
		case opNot:
			frame[i.a()] = boolValue(isFalse(frame[i.b()]))
		case opLength:
			tmp := l.objectLength(frame[i.b()])
			frame = ci.frame
			frame[i.a()] = tmp
		case opConcat:
			a, b, c := i.a(), i.b(), i.c()
			l.top = ci.stackIndex(c + 1) // mark the end of concat operands
			l.concat(c - b + 1)
			frame = ci.frame
			frame[a] = frame[b]
			if a >= b { // limit of live values
				clear(frame[a+1:])
			} else {
				clear(frame[b:])
			}
		case opJump:
			ip = l.jumpFrom(ci, i, ip)
		case opEqual:
			if l.equalObjects(k(i.b(), constants, frame), k(i.c(), constants, frame)) == (i.a() != 0) {
				ip = l.jumpFrom(ci, code[ip], ip+1)
			} else {
				ip++
			}
			frame = ci.frame
		case opLessThan:
			b, c := k(i.b(), constants, frame), k(i.c(), constants, frame)
			var less bool
			if b.isNumber() && c.isNumber() {
				less = b.f() < c.f()
			} else {
				less = l.lessThan(b, c)
				frame = ci.frame
			}
			if less == (i.a() != 0) {
				ip = l.jumpFrom(ci, code[ip], ip+1)
			} else {
				ip++
			}
		case opLessOrEqual:
			b, c := k(i.b(), constants, frame), k(i.c(), constants, frame)
			var lessOrEqual bool
			if b.isNumber() && c.isNumber() {
				lessOrEqual = b.f() <= c.f()
			} else {
				lessOrEqual = l.lessOrEqual(b, c)
				frame = ci.frame
			}
			if lessOrEqual == (i.a() != 0) {
				ip = l.jumpFrom(ci, code[ip], ip+1)
			} else {
				ip++
			}
		case opTest:
			if isFalse(frame[i.a()]) == (i.c() == 0) {
				ip = l.jumpFrom(ci, code[ip], ip+1)
			} else {
				ip++
			}
		case opTestSet:
			if b := frame[i.b()]; isFalse(b) == (i.c() == 0) {
				frame[i.a()] = b
				ip = l.jumpFrom(ci, code[ip], ip+1)
			} else {
				ip++
			}
		case opCall:
			a, b, c := i.a(), i.b(), i.c()
			if b > 1 && l.hookMask&(MaskCall|MaskReturn) == 0 {
				if f := frame[a].goFunction(); f != nil && f.number != nil {
					if nf := f.number; nf.unary != nil && b == 2 && c == 2 && frame[a+1].isNumber() {
						frame[a] = numberValue(nf.unary(frame[a+1].f()))
						l.top = ci.top
						break
					}
					if r, ok := f.number.tryCall(frame[a+1 : a+b]); ok {
						l.numberResult(ci, a, c-1, f.number.results, r)
						break
					}
				}
			}
			if b != 0 && l.hookMask&MaskCall == 0 {
				switch fv := frame[a]; fv.kind() {
				case vkLuaClosure:
					if f := fv.luaClosure(); !f.prototype.isVarArg {
						ci = l.callLua(ci, f, a, b-1, c-1)
						frame, closure, constants = ci.frame, f, f.prototype.constants
						code, ip = f.prototype.execCode(), 0
						continue
					}
				case vkGoFunction, vkGoClosure:
					l.top = ci.stackIndex(a + b)
					l.callGo(fv, ci.stackIndex(a), c-1)
					if c != 0 {
						l.top = ci.top // adjust results
					}
					frame = ci.frame
					continue
				}
			}
			if b != 0 {
				l.top = ci.stackIndex(a + b)
			} // else previous instruction set top
			if n := c - 1; l.preCall(ci.stackIndex(a), n) { // go function
				if n >= 0 {
					l.top = ci.top // adjust results
				}
				frame = ci.frame
			} else { // lua function
				ci = l.callInfo
				ci.setCallStatus(callStatusReentry)
				frame, closure, constants = newFrame(l, ci)
				code, ip = closure.prototype.execCode(), ci.savedPC
			}
		case opTailCall:
			a, b := i.a(), i.b()
			if b != 0 {
				l.top = ci.stackIndex(a + b)
			} // else previous instruction set top
			// TODO l.assert(i.c()-1 == MultipleReturns)
			if l.preCall(ci.stackIndex(a), MultipleReturns) { // go function
				frame = ci.frame
			} else {
				// tail call: put called frame (n) in place of caller one (o)
				nci := l.callInfo                      // called frame
				oci := nci.previous                    // caller frame
				nfn, ofn := nci.function, oci.function // called & caller function
				// last stack slot filled by 'precall'
				lim := nci.base() + l.stack[nfn].luaClosure().prototype.parameterCount
				if len(closure.prototype.prototypes) > 0 { // close all upvalues from previous call
					l.close(oci.base())
				}
				// move new frame into old one
				for i := 0; nfn+i < lim; i++ {
					l.stack[ofn+i] = l.stack[nfn+i]
				}
				base := ofn + (nci.base() - nfn) // correct base
				oci.setTop(ofn + (l.top - nfn))  // correct top
				oci.frame = l.stack[base:oci.top]
				oci.savedPC, oci.code, oci.closure = nci.savedPC, nci.code, nci.closure // correct code (savedPC indexes nci->code)
				oci.setCallStatus(callStatusTail)                                       // function was tail called
				l.top, l.callInfo, ci = oci.top, oci, oci
				// TODO l.assert(l.top == oci.base()+l.stack[ofn].(*luaClosure).prototype.maxStackSize)
				// TODO l.assert(&oci.frame[0] == &l.stack[oci.base()] && len(oci.frame) == oci.top-oci.base())
				frame, closure, constants = newFrame(l, ci)
				code, ip = closure.prototype.execCode(), ci.savedPC
			}
		case opReturn:
			a := i.a()
			if b, wanted := i.b(), ci.resultCount; b != 0 && wanted >= 0 && l.hookMask&(MaskReturn|MaskLine) == 0 && ci.isCallStatus(callStatusReentry) {
				// Fixed results into a Lua caller that wants a fixed count.
				if len(closure.prototype.prototypes) > 0 {
					l.close(ci.base())
				}
				res, results := l.stack[ci.function:ci.function+wanted], frame[a:a+b-1]
				n := copy(res, results)
				clear(res[n:])
				ci = ci.previous
				l.callInfo, l.top = ci, ci.top
				frame, closure, constants = newFrame(l, ci)
				code, ip = closure.prototype.execCode(), ci.savedPC
				break
			}
			if b := i.b(); b != 0 {
				l.top = ci.stackIndex(a + b - 1)
			}
			if len(closure.prototype.prototypes) > 0 {
				l.close(ci.base())
			}
			n := l.postCall(ci.stackIndex(a))
			if !ci.isCallStatus(callStatusReentry) { // ci still the called one?
				return // external invocation: return
			}
			ci = l.callInfo
			if n {
				l.top = ci.top
			}
			// TODO l.assert(ci.code[ci.savedPC-1].opCode() == opCall)
			frame, closure, constants = newFrame(l, ci)
			code, ip = closure.prototype.execCode(), ci.savedPC
		case opForLoop:
			a := i.a()
			index, limit, step := frame[a+0].f(), frame[a+1].f(), frame[a+2].f()
			if index += step; (0 < step && index <= limit) || (step <= 0 && limit <= index) {
				ip += pc(i.sbx())
				frame[a+0] = numberValue(index) // update internal index...
				frame[a+3] = numberValue(index) // ... and external index
			}
		case opForPrep:
			a := i.a()
			if init, ok := l.toNumber(frame[a+0]); !ok {
				l.runtimeError("'for' initial value must be a number")
			} else if limit, ok := l.toNumber(frame[a+1]); !ok {
				l.runtimeError("'for' limit must be a number")
			} else if step, ok := l.toNumber(frame[a+2]); !ok {
				l.runtimeError("'for' step must be a number")
			} else {
				frame[a+0], frame[a+1], frame[a+2] = numberValue(init-step), numberValue(limit), numberValue(step)
				ip += pc(i.sbx())
			}
		case opTForCall:
			a := i.a()
			callBase := a + 3
			copy(frame[callBase:callBase+3], frame[a:a+3])
			callBase += ci.base()
			l.top = callBase + 3 // function + 2 args (state and index)
			l.call(callBase, i.c(), true)
			frame, l.top = ci.frame, ci.top
			i = expectOp(code[ip], opTForLoop) // go to next instruction
			ip++
			ci.savedPC = ip
			fallthrough
		case opTForLoop:
			if a := i.a(); !frame[a+1].isNil() { // continue loop?
				frame[a] = frame[a+1] // save control variable
				ip += pc(i.sbx())     // jump back
			}
		case opSetList:
			a, n, c := i.a(), i.b(), i.c()
			if n == 0 {
				n = l.top - ci.stackIndex(a) - 1
			}
			if c == 0 {
				c = expectOp(code[ip], opExtraArg).ax()
				ip++
			}
			h := frame[a].table()
			start := (c - 1) * listItemsPerFlush
			last := start + n
			if last > len(h.array) {
				h.extendArray(last)
			}
			copy(h.array[start:last], frame[a+1:a+1+n])
			l.top = ci.top
		case opClosure:
			a, p := i.a(), &closure.prototype.prototypes[i.bx()]
			if ncl := cached(p, closure.upValues, ci.base()); ncl == nil { // no match?
				frame[a] = l.newClosure(p, closure.upValues, ci.base()) // create a new one
			} else {
				frame[a] = objectValue(ncl)
			}
			clear(frame[a+1:])
		case opVarArg:
			a, b := i.a(), i.b()-1
			n := ci.base() - ci.function - closure.prototype.parameterCount - 1
			if b < 0 {
				b = n // get all var arguments
				l.checkStack(n)
				l.top = ci.base() + a + n
				if ci.top < l.top {
					ci.setTop(l.top)
					ci.frame = l.stack[ci.base():ci.top]
				}
				frame = ci.frame
			}
			for j := range b {
				if j < n {
					frame[a+j] = l.stack[ci.base()-n+j]
				} else {
					frame[a+j] = nilValue
				}
			}
		case opExtraArg:
			panic(fmt.Sprintf("unexpected opExtraArg instruction, '%s'", i.String()))
		}
	}
}
