// Code generated by internal/jitvm/gen from vm.go; DO NOT EDIT.

package lua

import "fmt"
import "math"
import "github.com/matjam/luart/internal/bytecode"

// executeSwitchJIT is executeSwitch for states that compile. It runs
// compiled code when it reaches an instruction the JIT patched in.
func (l *State) executeSwitchJIT() {
	ci := l.callInfo
	frame, closure, constants := newFrame(l, ci)
	code, ip := closure.prototype.execCode(), ci.savedPC
	for {
		i := code[ip]
		ip++
		ci.savedPC = ip
		if l.hookMask&(MaskLine|MaskCount) != 0 {
			if l.hookCount--; l.hookCount == 0 || l.hookMask&MaskLine != 0 {
				l.traceExecution()
				frame = ci.frame
			}
		}
		if i.OpCode() >= opJITCount { // patched in by the JIT; see jit.go
			i, ip = l.jitInstruction(i, ip)
			ci = l.callInfo // compiled code may have called or returned
			frame, closure, constants = newFrame(l, ci)
			code = closure.prototype.execCode()
		}
		switch i.OpCode() {
		case bytecode.OpMove:
			frame[i.A()] = frame[i.B()]
		case bytecode.OpLoadConstant:
			frame[i.A()] = constants[i.Bx()]
		case bytecode.OpLoadConstantEx:
			frame[i.A()] = constants[expectOp(code[ip], bytecode.OpExtraArg).Ax()]
			ip++
		case bytecode.OpLoadBool:
			frame[i.A()] = boolValue(i.B() != 0)
			if i.C() != 0 {
				ip++
			}
		case bytecode.OpLoadNil:
			a, b := i.A(), i.B()
			clear(frame[a : a+b+1])
		case bytecode.OpGetUpValue:
			frame[i.A()] = closure.upValue(i.B())
		case bytecode.OpGetTableUp:
			tmp := l.tableAt(closure.upValue(i.B()), k(i.C(), constants, frame))
			frame = ci.frame
			frame[i.A()] = tmp
		case bytecode.OpGetTable:
			tmp := l.tableAt(frame[i.B()], k(i.C(), constants, frame))
			frame = ci.frame
			frame[i.A()] = tmp
		case bytecode.OpSetTableUp:
			l.setTableAt(closure.upValue(i.A()), k(i.B(), constants, frame), k(i.C(), constants, frame))
			frame = ci.frame
		case bytecode.OpSetUpValue:
			closure.setUpValue(i.B(), frame[i.A()])
		case bytecode.OpSetTable:
			l.setTableAt(frame[i.A()], k(i.B(), constants, frame), k(i.C(), constants, frame))
			frame = ci.frame
		case bytecode.OpNewTable:
			a := i.A()
			b, c := bytecode.IntFromFloat8(i.B()), bytecode.IntFromFloat8(i.C())
			frame[a] = objectValue(l.newTableAt(&closure.prototype.fields[ip-1], b, c))
			clear(frame[a+1:])
		case bytecode.OpSelf:
			a, t := i.A(), frame[i.B()]
			tmp := l.tableAt(t, k(i.C(), constants, frame))
			frame = ci.frame
			frame[a+1], frame[a] = t, tmp
		case opGetField:
			t, key := frame[i.B()], constants[i.C()]
			if v, ok := getField(t, key, &closure.prototype.fields[ip-1]); ok {
				frame[i.A()] = v
				break
			}
			tmp := l.tableAt(t, key)
			frame = ci.frame
			frame[i.A()] = tmp
		case opGetFieldUp:
			t, key := closure.upValue(i.B()), constants[i.C()]
			if v, ok := getField(t, key, &closure.prototype.fields[ip-1]); ok {
				frame[i.A()] = v
				break
			}
			tmp := l.tableAt(t, key)
			frame = ci.frame
			frame[i.A()] = tmp
		case opSelfField:
			a, t, key := i.A(), frame[i.B()], constants[i.C()]
			if v, ok := getField(t, key, &closure.prototype.fields[ip-1]); ok {
				frame[a+1], frame[a] = t, v
				break
			}
			tmp := l.tableAt(t, key)
			frame = ci.frame
			frame[a+1], frame[a] = t, tmp
		case opSetField:
			t, key, v := frame[i.A()], constants[i.B()], k(i.C(), constants, frame)
			if !setField(t, key, v, &closure.prototype.fields[ip-1]) {
				l.setTableAt(t, key, v)
				frame = ci.frame
			}
		case opSetFieldUp:
			t, key, v := closure.upValue(i.A()), constants[i.B()], k(i.C(), constants, frame)
			if !setField(t, key, v, &closure.prototype.fields[ip-1]) {
				l.setTableAt(t, key, v)
				frame = ci.frame
			}
		case bytecode.OpAdd:
			b, c := k(i.B(), constants, frame), k(i.C(), constants, frame)
			if b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() + c.f())
				break
			} else if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(b.i() + c.i())
				break
			}
			tmp := l.arith(b, c, tmAdd)
			frame = ci.frame
			frame[i.A()] = tmp
		case bytecode.OpSub:
			b, c := k(i.B(), constants, frame), k(i.C(), constants, frame)
			if b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() - c.f())
				break
			} else if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(b.i() - c.i())
				break
			}
			tmp := l.arith(b, c, tmSub)
			frame = ci.frame
			frame[i.A()] = tmp
		case bytecode.OpMul:
			b, c := k(i.B(), constants, frame), k(i.C(), constants, frame)
			if b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() * c.f())
				break
			} else if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(b.i() * c.i())
				break
			}
			tmp := l.arith(b, c, tmMul)
			frame = ci.frame
			frame[i.A()] = tmp
		case bytecode.OpDiv:
			b, c := k(i.B(), constants, frame), k(i.C(), constants, frame)
			if b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() / c.f())
				break
			} else if b.isNumber() && c.isNumber() {
				frame[i.A()] = numberValue(b.toFloat() / c.toFloat())
				break
			}
			tmp := l.arith(b, c, tmDiv)
			frame = ci.frame
			frame[i.A()] = tmp
		case bytecode.OpMod:
			b, c := k(i.B(), constants, frame), k(i.C(), constants, frame)
			if b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(bytecode.FloatMod(b.f(), c.f()))
				break
			} else if b.isInteger() && c.isInteger() && c.i() != 0 {
				frame[i.A()] = integerValue(bytecode.IntMod(b.i(), c.i()))
				break
			}
			tmp := l.arith(b, c, tmMod)
			frame = ci.frame
			frame[i.A()] = tmp
		case bytecode.OpPow:
			b, c := k(i.B(), constants, frame), k(i.C(), constants, frame)
			if b.isNumber() && c.isNumber() {
				frame[i.A()] = numberValue(bytecode.Pow(b.toFloat(), c.toFloat()))
				break
			}
			tmp := l.arith(b, c, tmPow)
			frame = ci.frame
			frame[i.A()] = tmp
		case bytecode.OpIDiv:
			b, c := k(i.B(), constants, frame), k(i.C(), constants, frame)
			if b.isInteger() && c.isInteger() && c.i() != 0 {
				frame[i.A()] = integerValue(bytecode.IntFloorDiv(b.i(), c.i()))
				break
			} else if b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(math.Floor(b.f() / c.f()))
				break
			}
			tmp := l.arith(b, c, tmIDiv)
			frame = ci.frame
			frame[i.A()] = tmp
		case bytecode.OpBitwise:
			op := bytecode.ArithOp(code[ip].Ax()) // the EXTRAARG after it
			ip++
			b := k(i.B(), constants, frame)
			c := b
			if op != bytecode.ArithBNot {
				c = k(i.C(), constants, frame)
			}
			if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(bytecode.IntBitwise(op, b.i(), c.i()))
				break
			}
			tmp := l.arith(b, c, arithEvent(op))
			frame = ci.frame
			frame[i.A()] = tmp
		case opAddRR:
			if b, c := frame[i.B()], frame[i.C()]; b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() + c.f())
			} else if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(b.i() + c.i())
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmAdd)
			}
		case opAddRK:
			if b, c := frame[i.B()], constants[i.C()]; b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() + c.f())
			} else if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(b.i() + c.i())
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmAdd)
			}
		case opAddKR:
			if b, c := constants[i.B()], frame[i.C()]; b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() + c.f())
			} else if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(b.i() + c.i())
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmAdd)
			}
		case opMulAddRKR:
			if b, c := frame[i.B()], constants[i.C()]; b.isFloat() && c.isFloat() {
				r := float64(b.f() * c.f()) // rounded: Go may fuse x*y + z otherwise, as C Lua does not
				frame[i.A()] = numberValue(r)
				if j := code[ip]; l.hookMask&(MaskLine|MaskCount) == 0 {
					if d := frame[j.C()]; d.isFloat() {
						frame[j.A()] = numberValue(r + d.f())
						ip++
					}
				}
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmMul)
			}
		case opSubRR:
			if b, c := frame[i.B()], frame[i.C()]; b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() - c.f())
			} else if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(b.i() - c.i())
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmSub)
			}
		case opSubRK:
			if b, c := frame[i.B()], constants[i.C()]; b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() - c.f())
			} else if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(b.i() - c.i())
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmSub)
			}
		case opSubKR:
			if b, c := constants[i.B()], frame[i.C()]; b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() - c.f())
			} else if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(b.i() - c.i())
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmSub)
			}
		case opMulRR:
			if b, c := frame[i.B()], frame[i.C()]; b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() * c.f())
			} else if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(b.i() * c.i())
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmMul)
			}
		case opMulRK:
			if b, c := frame[i.B()], constants[i.C()]; b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() * c.f())
			} else if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(b.i() * c.i())
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmMul)
			}
		case opMulKR:
			if b, c := constants[i.B()], frame[i.C()]; b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() * c.f())
			} else if b.isInteger() && c.isInteger() {
				frame[i.A()] = integerValue(b.i() * c.i())
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmMul)
			}
		case opDivRR:
			if b, c := frame[i.B()], frame[i.C()]; b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() / c.f())
			} else if b.isNumber() && c.isNumber() {
				frame[i.A()] = numberValue(b.toFloat() / c.toFloat())
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmDiv)
			}
		case opDivRK:
			if b, c := frame[i.B()], constants[i.C()]; b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() / c.f())
			} else if b.isNumber() && c.isNumber() {
				frame[i.A()] = numberValue(b.toFloat() / c.toFloat())
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmDiv)
			}
		case opDivKR:
			if b, c := constants[i.B()], frame[i.C()]; b.isFloat() && c.isFloat() {
				frame[i.A()] = numberValue(b.f() / c.f())
			} else if b.isNumber() && c.isNumber() {
				frame[i.A()] = numberValue(b.toFloat() / c.toFloat())
			} else {
				frame = l.arithInto(ci, i.A(), b, c, tmDiv)
			}
		case bytecode.OpUnaryMinus:
			if b := frame[i.B()]; b.isFloat() {
				frame[i.A()] = numberValue(-b.f())
			} else if b.isInteger() {
				frame[i.A()] = integerValue(-b.i())
			} else {
				tmp := l.arith(b, b, tmUnaryMinus)
				frame = ci.frame
				frame[i.A()] = tmp
			}
		case bytecode.OpNot:
			frame[i.A()] = boolValue(isFalse(frame[i.B()]))
		case bytecode.OpLength:
			tmp := l.objectLength(frame[i.B()])
			frame = ci.frame
			frame[i.A()] = tmp
		case bytecode.OpConcat:
			a, b, c := i.A(), i.B(), i.C()
			l.top = ci.stackIndex(c + 1) // mark the end of concat operands
			l.concat(c - b + 1)
			frame = ci.frame
			frame[a] = frame[b]
			if a >= b { // limit of live values
				clear(frame[a+1:])
			} else {
				clear(frame[b:])
			}
		case bytecode.OpJump:
			ip = l.jumpFrom(ci, i, ip)
			frame = ci.frame // a __close may move the stack
		case bytecode.OpTBC:
			if a := i.A(); i.B() != 0 { // a generic for: closing value below the control variable
				frame[a], frame[a+1] = frame[a+1], frame[a]
			}
			l.newTBC(ci, i.A())
		case bytecode.OpEqual:
			if l.equalObjects(k(i.B(), constants, frame), k(i.C(), constants, frame)) == (i.A() != 0) {
				ip = l.jumpFrom(ci, code[ip], ip+1)
				frame = ci.frame // a __close may move the stack
			} else {
				ip++
			}
			frame = ci.frame
		case bytecode.OpLessThan:
			b, c := k(i.B(), constants, frame), k(i.C(), constants, frame)
			var less bool
			if b.isFloat() && c.isFloat() {
				less = b.f() < c.f()
			} else if b.isInteger() && c.isInteger() {
				less = b.i() < c.i()
			} else {
				less = l.lessThan(b, c)
				frame = ci.frame
			}
			if less == (i.A() != 0) {
				ip = l.jumpFrom(ci, code[ip], ip+1)
				frame = ci.frame // a __close may move the stack
			} else {
				ip++
			}
		case bytecode.OpLessOrEqual:
			b, c := k(i.B(), constants, frame), k(i.C(), constants, frame)
			var lessOrEqual bool
			if b.isFloat() && c.isFloat() {
				lessOrEqual = b.f() <= c.f()
			} else if b.isInteger() && c.isInteger() {
				lessOrEqual = b.i() <= c.i()
			} else {
				lessOrEqual = l.lessOrEqual(b, c)
				frame = ci.frame
			}
			if lessOrEqual == (i.A() != 0) {
				ip = l.jumpFrom(ci, code[ip], ip+1)
				frame = ci.frame // a __close may move the stack
			} else {
				ip++
			}
		case bytecode.OpTest:
			if isFalse(frame[i.A()]) == (i.C() == 0) {
				ip = l.jumpFrom(ci, code[ip], ip+1)
				frame = ci.frame // a __close may move the stack
			} else {
				ip++
			}
		case bytecode.OpTestSet:
			if b := frame[i.B()]; isFalse(b) == (i.C() == 0) {
				frame[i.A()] = b
				ip = l.jumpFrom(ci, code[ip], ip+1)
				frame = ci.frame // a __close may move the stack
			} else {
				ip++
			}
		case bytecode.OpCall:
			a, b, c := i.A(), i.B(), i.C()
			if b > 1 && l.hookMask&(MaskCall|MaskReturn) == 0 {
				if f := frame[a].goFunction(); f != nil && f.number != nil {
					if nf := f.number; nf.unary != nil && b == 2 && c == 2 && frame[a+1].isNumber() {
						frame[a] = numberValue(nf.unary(frame[a+1].toFloat()))
						l.top = ci.top
						break
					}
					if r, ok := f.number.tryCall(frame[a+1 : a+b]); ok {
						l.numberResult(ci, a, c-1, f.number.results, r)
						break
					}
				}
			}
			if b != 0 && l.hookMask&MaskCall == 0 {
				switch fv := frame[a]; fv.kind() {
				case vkLuaClosure:
					if f := fv.luaClosure(); !f.prototype.IsVarArg {
						ci = l.callLua(ci, f, a, b-1, c-1)
						frame, closure, constants = ci.frame, f, f.prototype.Constants
						code, ip = f.prototype.execCode(), 0
						continue
					}
				case vkGoFunction, vkGoClosure:
					l.top = ci.stackIndex(a + b)
					l.callGo(fv, ci.stackIndex(a), c-1)
					if c != 0 {
						l.top = ci.top // adjust results
					}
					frame = ci.frame
					continue
				}
			}
			if b != 0 {
				l.top = ci.stackIndex(a + b)
			} // else previous instruction set top
			if n := c - 1; l.preCall(ci.stackIndex(a), n) { // go function
				if n >= 0 {
					l.top = ci.top // adjust results
				}
				frame = ci.frame
			} else { // lua function
				ci = l.callInfo
				ci.setCallStatus(callStatusReentry)
				frame, closure, constants = newFrame(l, ci)
				code, ip = closure.prototype.execCode(), ci.savedPC
			}
		case bytecode.OpTailCall:
			l.pollInterrupt() // a loop of tail calls has no back-edge
			a, b := i.A(), i.B()
			if b != 0 {
				l.top = ci.stackIndex(a + b)
			} // else previous instruction set top
			// TODO l.assert(i.c()-1 == MultipleReturns)
			if l.preCall(ci.stackIndex(a), MultipleReturns) { // go function
				frame = ci.frame
			} else {
				// tail call: put called frame (n) in place of caller one (o)
				nci := l.callInfo                      // called frame
				oci := nci.previous                    // caller frame
				nfn, ofn := nci.function, oci.function // called & caller function
				// last stack slot filled by 'precall'
				lim := nci.base() + l.stack[nfn].luaClosure().prototype.ParameterCount
				if len(closure.prototype.Prototypes) > 0 { // close all upvalues from previous call
					l.close(oci.base())
				}
				// move new frame into old one
				for i := 0; nfn+i < lim; i++ {
					l.stack[ofn+i] = l.stack[nfn+i]
				}
				base := ofn + (nci.base() - nfn) // correct base
				oci.setTop(ofn + (l.top - nfn))  // correct top
				oci.frame = l.stack[base:oci.top]
				oci.savedPC, oci.code, oci.closure = nci.savedPC, nci.code, nci.closure // correct code (savedPC indexes nci->code)
				oci.setCallStatus(callStatusTail)                                       // function was tail called
				l.top, l.callInfo, ci = oci.top, oci, oci
				// TODO l.assert(l.top == oci.base()+l.stack[ofn].(*luaClosure).prototype.maxStackSize)
				// TODO l.assert(&oci.frame[0] == &l.stack[oci.base()] && len(oci.frame) == oci.top-oci.base())
				frame, closure, constants = newFrame(l, ci)
				code, ip = closure.prototype.execCode(), ci.savedPC
			}
		case bytecode.OpReturn:
			a := i.A()
			if l.hasTBC(ci.base()) {
				frame = l.closeForReturn(ci, i)
			}
			if b, wanted := i.B(), ci.resultCount; b != 0 && wanted >= 0 && l.hookMask&(MaskReturn|MaskLine) == 0 && ci.isCallStatus(callStatusReentry) {
				// Fixed results into a Lua caller that wants a fixed count.
				if len(closure.prototype.Prototypes) > 0 {
					l.close(ci.base())
				}
				res, results := l.stack[ci.function:ci.function+wanted], frame[a:a+b-1]
				n := copy(res, results)
				clear(res[n:])
				ci = ci.previous
				l.callInfo, l.top = ci, ci.top
				frame, closure, constants = newFrame(l, ci)
				code, ip = closure.prototype.execCode(), ci.savedPC
				break
			}
			if b := i.B(); b != 0 {
				l.top = ci.stackIndex(a + b - 1)
			}
			if len(closure.prototype.Prototypes) > 0 {
				l.close(ci.base())
			}
			n := l.postCall(ci.stackIndex(a))
			if !ci.isCallStatus(callStatusReentry) { // ci still the called one?
				return // external invocation: return
			}
			ci = l.callInfo
			if n {
				l.top = ci.top
			}
			// TODO l.assert(ci.code[ci.savedPC-1].opCode() == opCall)
			frame, closure, constants = newFrame(l, ci)
			code, ip = closure.prototype.execCode(), ci.savedPC
		case bytecode.OpForLoop:
			// See forPrep. An integer loop counts down the iterations left in
			// the limit's register; a float loop compares with the limit.
			a := i.A()
			if step := frame[a+2]; step.isInteger() {
				if count := uint64(frame[a+1].i()); count > 0 {
					l.pollInterrupt()
					index := integerValue(frame[a].i() + step.i())
					frame[a+1] = integerValue(int64(count - 1))
					frame[a], frame[a+3] = index, index
					ip += pc(i.SBx())
				}
			} else if index, limit, step := frame[a].f()+step.f(), frame[a+1].f(), step.f(); (0 < step && index <= limit) || (step <= 0 && limit <= index) {
				l.pollInterrupt()
				ip += pc(i.SBx())
				frame[a+0] = numberValue(index) // update internal index...
				frame[a+3] = numberValue(index) // ... and external index
			}
		case bytecode.OpForPrep:
			if l.forPrep(frame[i.A():]) {
				ip += pc(i.SBx()) + 1 // past the FORLOOP: the loop runs no times
			}
		case bytecode.OpTForCall:
			a := i.A()
			// Iterator, state and closing value at a, the control variable
			// at a+3, where the call goes so that its first result is the
			// new control value.
			callBase := a + 3
			frame[a+5] = frame[a+3] // control
			frame[a+4] = frame[a+1] // state
			frame[a+3] = frame[a]   // iterator
			callBase += ci.base()
			l.top = callBase + 3 // function + 2 args (state and index)
			l.call(callBase, i.C(), true)
			frame, l.top = ci.frame, ci.top
			i = expectOp(code[ip], bytecode.OpTForLoop) // go to next instruction
			ip++
			ci.savedPC = ip
			fallthrough
		case bytecode.OpTForLoop:
			if a := i.A(); !frame[a+3].isNil() { // continue loop? The control variable is the first result.
				l.pollInterrupt()
				ip += pc(i.SBx()) // jump back
			}
		case bytecode.OpSetList:
			a, n, c := i.A(), i.B(), i.C()
			if n == 0 {
				n = l.top - ci.stackIndex(a) - 1
			}
			if c == 0 {
				c = expectOp(code[ip], bytecode.OpExtraArg).Ax()
				ip++
			}
			h := frame[a].table()
			start := (c - 1) * bytecode.ListItemsPerFlush
			last := start + n
			if last > len(h.array) {
				h.extendArray(last)
			}
			copy(h.array[start:last], frame[a+1:a+1+n])
			l.top = ci.top
		case bytecode.OpClosure:
			a, p := i.A(), &closure.prototype.Prototypes[i.Bx()]
			if ncl := cached(p, closure.upValues, ci.base()); ncl == nil { // no match?
				frame[a] = l.newClosure(p, closure.upValues, ci.base()) // create a new one
			} else {
				frame[a] = objectValue(ncl)
			}
			clear(frame[a+1:])
		case bytecode.OpVarArg:
			a, b := i.A(), i.B()-1
			n := ci.base() - ci.function - closure.prototype.ParameterCount - 1
			if b < 0 {
				b = n // get all var arguments
				l.checkStack(n)
				l.top = ci.base() + a + n
				if ci.top < l.top {
					ci.setTop(l.top)
					ci.frame = l.stack[ci.base():ci.top]
				}
				frame = ci.frame
			}
			for j := range b {
				if j < n {
					frame[a+j] = l.stack[ci.base()-n+j]
				} else {
					frame[a+j] = nilValue
				}
			}
		case bytecode.OpErrNNil:
			if !frame[i.A()].isNil() {
				name := "?"
				if bx := i.Bx(); bx > 0 {
					name, _ = constants[bx-1].str()
				}
				l.runtimeError(fmt.Sprintf("global '%s' already defined", name))
			}
		case bytecode.OpExtraArg:
			panic(fmt.Sprintf("unexpected opExtraArg instruction, '%s'", i.String()))
		}
	}
}
