// Package jitvm generates vm_jit.go: a copy of the interpreter loop,
// executeSwitch in vm.go, that hands over to compiled code at instructions
// the JIT patched in.
//
// The copy exists because any extra work in the loop measured 5–10%
// slower, so states without the JIT keep the loop unchanged. Run go
// generate after editing executeSwitch; TestJITInterpreterIsGenerated fails
// while the copy is stale.
package jitvm

import (
	"bytes"
	"fmt"
	"go/format"
)

const (
	start    = "func (l *State) executeSwitch() {\n"
	dispatch = "\t\tswitch i.opCode() {\n"
	hook     = "\t\tif i.opCode() >= opJITCount { // patched in by the JIT; see jit.go\n" +
		"\t\t\ti, ip = l.jitInstruction(i, ip)\n" +
		"\t\t\tci = l.callInfo // compiled code may have called or returned\n" +
		"\t\t\tframe, closure, constants = newFrame(l, ci)\n" +
		"\t\t\tcode = closure.prototype.execCode()\n" +
		"\t\t}\n"
)

// Generate returns vm_jit.go for the given vm.go.
func Generate(vm []byte) ([]byte, error) {
	i := bytes.Index(vm, []byte(start))
	if i < 0 {
		return nil, fmt.Errorf("jitvm: executeSwitch not found")
	}
	end := bytes.Index(vm[i:], []byte("\n}\n"))
	if end < 0 {
		return nil, fmt.Errorf("jitvm: end of executeSwitch not found")
	}
	body := vm[i+len(start) : i+end+3]
	if bytes.Count(body, []byte(dispatch)) != 1 {
		return nil, fmt.Errorf("jitvm: want exactly one dispatch switch in executeSwitch")
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by internal/jitvm/gen from vm.go; DO NOT EDIT.\n\n")
	b.WriteString("package luart\n\n")
	for _, path := range imports(vm) {
		name := path[bytes.LastIndexByte(path, '/')+1:]
		if bytes.Contains(body, append(append([]byte(nil), name...), '.')) {
			fmt.Fprintf(&b, "import %q\n", path)
		}
	}
	b.WriteString("\n")
	b.WriteString("// executeSwitchJIT is executeSwitch for states that compile. It runs\n")
	b.WriteString("// compiled code when it reaches an instruction the JIT patched in.\n")
	b.WriteString("func (l *State) executeSwitchJIT() {\n")
	b.Write(bytes.Replace(body, []byte(dispatch), []byte(hook+dispatch), 1))
	return format.Source(b.Bytes())
}

// imports returns the paths in vm.go's parenthesised import block.
func imports(vm []byte) [][]byte {
	i := bytes.Index(vm, []byte("import (\n"))
	if i < 0 {
		return nil
	}
	block := vm[i+len("import (\n"):]
	block = block[:bytes.IndexByte(block, ')')]
	var paths [][]byte
	for _, line := range bytes.Split(block, []byte("\n")) {
		if line = bytes.Trim(bytes.TrimSpace(line), `"`); len(line) > 0 {
			paths = append(paths, line)
		}
	}
	return paths
}
